name: Schedule sync all

on:
  schedule:
    - cron:  '0 * * * *'

# These are required to authenticate Kahoy against a cluster.
env:
  K8S_CA: ${{secrets.K8S_CA}}
  K8S_SERVER: ${{secrets.K8S_SERVER}}
  K8S_SA_TOKEN: ${{secrets.K8S_SA_TOKEN}}

jobs:
  deploy-all:
    if: github.ref == 'refs/heads/master'
    name: sync
    runs-on: ubuntu-latest
    container: slok/kahoy:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      #- run: ./scripts/ci/k8s-auth.sh
      - run: ./scripts/ci/deploy.sh sync-all